version: '3'

services:
  db:
    container_name: db
    image: postgres:9.5
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    ports:
      - 5437:5432
    restart: unless-stopped
    networks:
      - app

  back-end:
    container_name: back-end
    build: ./back-end
    env_file:
      - .env
    environment:
      POSTGRES_DB_ENDPOINT: db
    volumes:
      - ./dist:/dist
    ports:
      - 5000:5000
    restart: unless-stopped
    networks:
      - app

networks:
    app:
        driver: bridge
