version: '3'

services:
  db:
    container_name: db
    image: postgres:9.5
    env_file:
      - .env
    ports:
      - 5437:5432
    restart: unless-stopped
    networks:
      - app

  back-end:
    container_name: back-end
    build: ./back-end
    env_file:
      - .env
    environment:
      POSTGRES_DB_ENDPOINT: db
    volumes:
      - ./dist:/dist
    restart: unless-stopped
    volumes:
      - ./static:/static
    networks:
      - app

networks:
    app:
        driver: bridge
