"""relations

Revision ID: 48e7c658a8b4
Revises: 860730292396
Create Date: 2019-06-11 14:19:01.194631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e7c658a8b4'
down_revision = '860730292396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'accounts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_to_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_from_id'], ['id'])
    op.add_column('users', sa.Column('role_id', sa.BigInteger(), nullable=False))
    op.create_unique_constraint(None, 'users', ['login'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'role_id')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    # ### end Alembic commands ###
