"""currency_rates_table

Revision ID: 5bd523bb2d46
Revises: 3a495d0928ab
Create Date: 2019-06-11 14:20:40.922978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd523bb2d46'
down_revision = '3a495d0928ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_rates',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('currency_from_id', sa.BigInteger(), nullable=False),
    sa.Column('currency_to_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['currency_from_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['currency_to_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('currency_from_id', 'currency_to_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency_rates')
    # ### end Alembic commands ###
