"""initial

Revision ID: f8ccd040e4bb
Revises: 
Create Date: 2019-06-11 18:41:01.812790

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f8ccd040e4bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('ticker', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_currencies'))
                    )
    op.create_table('fees',
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('type', sa.BigInteger(), nullable=False),
                    sa.Column('percent', sa.Numeric(), server_default='0', nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_fees')),
                    sa.UniqueConstraint('type', name=op.f('uq_fees_type'))
                    )
    op.create_table('roles',
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
                    )
    op.create_table('currency_rates',
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('currency_from_id', sa.BigInteger(), nullable=False),
                    sa.Column('currency_to_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['currency_from_id'], ['currencies.id'],
                                            name=op.f('fk_currency_rates_currency_from_id_currencies')),
                    sa.ForeignKeyConstraint(['currency_to_id'], ['currencies.id'],
                                            name=op.f('fk_currency_rates_currency_to_id_currencies')),
                    sa.PrimaryKeyConstraint('currency_from_id', 'currency_to_id', name=op.f('pk_currency_rates'))
                    )
    op.create_table('users',
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('login', sa.Text(), nullable=False),
                    sa.Column('password', sa.Text(), nullable=False),
                    sa.Column('salt', sa.Text(), nullable=False),
                    sa.Column('role_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
                    sa.UniqueConstraint('login', name=op.f('uq_users_login'))
                    )
    op.create_table('accounts',
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('balance', sa.Numeric(), nullable=False),
                    sa.Column('currency_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_accounts_user_id_users')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
                    )
    op.create_table('events',
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('type', sa.BigInteger(), nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('account_from_id', sa.BigInteger(), nullable=False),
                    sa.Column('account_to_id', sa.BigInteger(), nullable=False),
                    sa.Column('account_to_idd', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['account_from_id'], ['accounts.id'],
                                            name=op.f('fk_events_account_from_id_accounts')),
                    sa.ForeignKeyConstraint(['account_to_id'], ['accounts.id'],
                                            name=op.f('fk_events_account_to_id_accounts')),
                    sa.ForeignKeyConstraint(['account_to_idd'], ['accounts.id'],
                                            name=op.f('fk_events_account_to_idd_accounts')),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_events_user_id_users')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
                    )
    op.create_table('transactions',
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('value', sa.Numeric(), nullable=False),
                    sa.Column('event_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_transactions_event_id_events')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('events')
    op.drop_table('accounts')
    op.drop_table('users')
    op.drop_table('currency_rates')
    op.drop_table('roles')
    op.drop_table('fees')
    op.drop_table('currencies')
    # ### end Alembic commands ###
